## Register an admin or a parent

POST http://localhost:5500/api/auth/register
Content-Type: application/json

{
    "firstName":"",
    "lastName":"",
    "email":"",
    "phoneNumber":100,
    "role":"super_admin",
    "password":""
}

### Signin a parent / admin

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email":"",
    "password":""
}

### Signin a student

POST http://localhost:3000/api/auth/child/signin
Content-Type: application/json

{
    "firstName":"",
    "password":""
}
